---
- name: Setup docker swarm on base
  hosts: base

  tasks:
    - name: Install docker
      ansible.builtin.import_role:
        name: docker_setup

    - name: Init a new swarm with default parameters
      community.docker.docker_swarm:
        state: present
        advertise_addr: "{{ ansible_default_ipv4['address'] }}"
      become: true

    - name: Setup traefik
      ansible.builtin.import_role:
        name: traefik_setup
      vars:
        traefik_setup_version: "{{ traefik_version }}"

    - name: Setup Technitium
      ansible.builtin.import_role:
        name: technitium_setup
      vars:
        technitium_setup_version: "{{ technitium_version }}"
        technitium_setup_dashboard_password: "{{ dns_dashboard_password }}"
        technitium_setup_smb_user: "{{ dns_smb_user }}"
        technitium_setup_smb_pass: "{{ (samba_users | items2dict(key_name='name', value_name='pass'))[dns_smb_user] }}"
        # 'base' will always be the SMB/NAS server so even if we run this on another host, we want to use base's IP here
        technitium_setup_smb_path: "//{{ hostvars['base']['ansible_default_ipv4']['address'] }}/{{ dns_smb_user }}"
