---
- name: Setup docker swarm on base
  hosts: base.home

  tasks:
    - name: Install docker
      ansible.builtin.import_role:
        name: docker_setup
      vars:
        docker_setup_dns: "{{ docker_dns }}"
    - name: Init a new swarm with default parameters
      community.docker.docker_swarm:
        state: present
        advertise_addr: "{{ ansible_default_ipv4['address'] }}"
      become: true

    - name: Setup traefik
      ansible.builtin.import_role:
        name: traefik_setup
      vars:
        traefik_setup_socket_proxy_version: "{{ socket_proxy_version }}"
        traefik_setup_version: "{{ traefik_version }}"

    - name: Setup Technitium
      ansible.builtin.import_role:
        name: technitium_setup
      vars:
        technitium_setup_version: "{{ technitium_version }}"
        technitium_setup_dashboard_password: "{{ dns_dashboard_password }}"
        technitium_setup_smb_user: "{{ dns_smb_user }}"
        technitium_setup_smb_pass: "{{ (samba_users | items2dict(key_name='name', value_name='pass'))[dns_smb_user] }}"
        # 'base.home' will always be the SMB/NAS server so even if we run this on another host, we want to use base's IP here
        technitium_setup_smb_path: "//{{ hostvars['base.home']['ansible_default_ipv4']['address'] }}/{{ dns_smb_user }}"
        # Maria DB
        technitium_setup_mariadb_version: "{{ mariadb_version }}"
        technitium_setup_mariadb_password: "{{ mariadb_root_password }}"
        technitium_setup_mariadb_master_placement_hostname: "base"

    - name: Setup miscellaneous utils
      ansible.builtin.import_role:
        name: utils_setup
      vars:
        utils_setup_stirling_version: "{{ stirling_version }}"
        utils_setup_smb_user: "{{ utils_smb_user }}"
        utils_setup_smb_pass: "{{ (samba_users | items2dict(key_name='name', value_name='pass'))[utils_smb_user] }}"
        # 'base.home' will always be the SMB/NAS server so even if we run this on another host, we want to use base's IP here
        utils_setup_smb_path: "//{{ hostvars['base.home']['ansible_default_ipv4']['address'] }}/{{ utils_smb_user }}"

    - name: Setup media stack
      ansible.builtin.import_role:
        name: media_setup
      vars:
        media_setup_jellyfin_version: "{{ jellyfin_version }}"
        media_setup_qbittorrent_version: "{{ qbittorrent_version }}"
        media_setup_radarr_version: "{{ radarr_version }}"
        media_setup_sonarr_version: "{{ sonarr_version }}"
        media_setup_bazarr_version: "{{ bazarr_version }}"
        media_setup_prowlarr_version: "{{ prowlarr_version }}"
        media_setup_media_path: "{{ media_path }}"
        media_setup_hw_acc_dev: "{{ media_hw_acc_dev }}"
        media_setup_placement_hostname: "base"

    - name: Setup guac stack
      ansible.builtin.import_role:
        name: guac_setup
      vars:
        guac_setup_mariadb_version: "{{ guac_mariadb_version }}"
        guac_setup_web_version: "{{ guac_web_version }}"
        guac_setup_daemon_version: "{{ guac_daemon_version }}"
        guac_setup_mariadb_root_pwd: "{{ guac_mariadb_root_pwd }}"
        guac_setup_mariadb_guac_pwd: "{{ guac_mariadb_guacusr_pwd }}"
        guac_setup_mariadb_master_placement_hostname: "base"

    - name: Setup Wireguard VPN
      ansible.builtin.import_role:
        name: wg_setup
      vars:
        wg_setup_version: "{{ wg_version }}"
        wg_setup_smb_user: "{{ vpn_smb_user }}"
        wg_setup_smb_pass: "{{ (samba_users | items2dict(key_name='name', value_name='pass'))[vpn_smb_user] }}"
        # 'base.home' will always be the SMB/NAS server so even if we run this on another host, we want to use base's IP here
        wg_setup_smb_path: "//{{ hostvars['base.home']['ansible_default_ipv4']['address'] }}/{{ vpn_smb_user }}"
