[project]
name = "homelab-setup"
version = "0.1.0"
description = ""
authors = [{ name = "Andreas Georgiou" }]
requires-python = ">=3.11,<4"
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dependencies = [
    "ansible>=11.1.0,<12",
]

[dependency-groups]
dev = [
    "ansible-dev-tools>=24.12.0,<25",
    "ansible-lint>=24.12.2,<25 ; platform_system != 'Windows'",
]

[tool.uv]
package = false
default-groups = "all"
environments = ["platform_system != 'Windows'"]

[build-system]
requires = ["uv_build>=0.10.0,<0.11.0"]
build-backend = "uv_build"
