---
- name: Ensure prerequisites are installed
  ansible.builtin.apt:
    name: ["ca-certificates", "curl"]
    state: present
    update_cache: true

- name: Create keyrings directory
  ansible.builtin.file:
    path: "/etc/apt/keyrings"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Download docker's GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: "0644"

- name: Add docker repository to apt
  ansible.builtin.deb822_repository:
    name: docker
    types:
      - deb
    uris: https://download.docker.com/linux/debian
    suites: "{{ ansible_distribution_release }}"
    components:
      - stable
    architectures: "{{ arch_map[ansible_architecture] | default(ansible_architecture) }}"
    signed_by: /etc/apt/keyrings/docker.asc
  vars:
    arch_map: { "x86_64": "amd64" }

- name: Install docker
  ansible.builtin.apt:
    name: ["docker-ce", "docker-ce-cli", "containerd.io", "docker-buildx-plugin", "docker-compose-plugin", "python3-docker"]
    state: present
    update_cache: true

- name: Modify docker DNS
  ansible.builtin.template:
    src: templates/daemon.json.j2
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: "0644"
