---
- name: Ensure that the latest version of openssh-server is installed
  ansible.builtin.apt:
    name: "openssh-server"
    state: latest # noqa package-latest
    update_cache: true

- name: Create /etc/ssh/sshd_config.d/99_sshd_config.conf
  ansible.builtin.template:
    src: templates/99_sshd_config.conf.j2
    dest: /etc/ssh/sshd_config.d/99_sshd_config.conf
    mode: "0644"
