- name: Fetch all filenames in /etc/logrotate.d/
  ansible.builtin.find:
    paths: /etc/logrotate.d/
  register: find_result

- name: Comment out compress keyword in /etc/logrotate.d/*
  ansible.builtin.replace:
    path: "{{ item }}"
    regexp: '(^|[^#y])(compress)'
    replace: '\1#\2'
  loop: "{{ find_result.files | map(attribute='path') }}"
