---
# zfs_main
zfs_main_pool_name: "tank"
zfs_main_pool_options:
  - "ashift=12"
  - "autotrim=on"
zfs_main_pool_mountpoint: "none"
zfs_main_pool_mode: "raidz1"
zfs_main_pool_devices:
  - "/dev/disk/by-id/ata-CT2000MX500SSD1_2431E8BDAE17"
  - "/dev/disk/by-id/ata-CT2000MX500SSD1_2431E8BDADFA"
  - "/dev/disk/by-id/ata-CT2000MX500SSD1_2431E8BDAE00"
zfs_main_pool_root_dataset_options:
  - "xattr=sa"
  - "dnodesize=auto"
  - "atime=off"
  - "recordsize=1M"
  - "snapdir=visible"
  - "normalization=formD"
  - "compression=lz4"
  - "canmount=off"
zfs_main_pool_encryption_passphrase: "{{ vault_zfs_main_pool_encryption_passphrase }}"

# cockpit
cockpit_server_is_primary: true

# samba
samba_users: "{{ vault_samba_users }}"
samba_root: "/tank/samba"

# technitium
dns_smb_user: "{{ vault_dns_smb_user }}"
dns_dashboard_password: "{{ vault_dns_dashboard_password }}"
